name: Sanitizers

on: [push, pull_request]

jobs:
  linux-sanitizers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Build with ASan
        run: |
          cmake -B build-asan -S . \
            -DCMAKE_C_FLAGS="-fsanitize=address -fno-omit-frame-pointer -O1 -g" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address"
          cmake --build build-asan

      - name: Create test data
        run: |
          mkdir -p build-asan/bin
          echo "10 20 30" > build-asan/bin/data.txt
          echo "5 15 25" >> build-asan/bin/data.txt

      - name: Run with ASan
        run: |
          cd build-asan/bin
          ./parent data.txt ./child

      - name: Build for Valgrind
        run: |
          cmake -B build-valgrind -S . -DCMAKE_BUILD_TYPE=Debug
          cmake --build build-valgrind
          mkdir -p build-valgrind/bin
          echo "10 20 30" > build-valgrind/bin/data.txt
          echo "5 15 25" >> build-valgrind/bin/data.txt

      - name: Run with Valgrind
        run: |
          cd build-valgrind/bin
          valgrind --leak-check=full --error-exitcode=1 --trace-children=yes ./parent data.txt ./child

  windows-sanitizers:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Build and Analyze Leaks
        shell: pwsh
        run: |
          cmake -B build-analyze -S . `
           -DCMAKE_C_FLAGS="/analyze /WX /D_CRT_SECURE_NO_WARNINGS" `
           -DCMAKE_CXX_FLAGS="/analyze /WX /D_CRT_SECURE_NO_WARNINGS"
          

          cmake --build build-analyze

      - name: Create test data
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path build-analyze/bin/Debug
          "10 20 30" | Out-File -FilePath build-analyze/bin/Debug/data.txt -Encoding utf8NoBOM
          "5 15 25" | Out-File -FilePath build-analyze/bin/Debug/data.txt -Append -Encoding utf8NoBOM

      - name: Run (Functional Test)
        shell: pwsh
        run: |
          $binDir = (Get-Item "build-analyze/bin/Debug").FullName
          $env:PATH = "$binDir;" + $env:PATH
          cd $binDir
          $childPath = (Get-Item "child.exe").FullName
          $parentPath = (Get-Item "parent.exe").FullName
          
          & $parentPath data.txt $childPath

